### ISSUE TITLE
Ineald Needs a Job

### ISSUE THREAD

**Issue by coder0xff** [AtaxiaGames-GM/AtaxiaCraft#8]
NPC Ineald, the mining foreman, stands around in the guild hall all day longing for purpose.

**Comment by AtaxiaGames-GM** [comment]
Will attempt to do this when I get home (in about 3 hours).

**Comment by AtaxiaGames-GM** [comment]
Actually, I'm not sure what it is you are asking me to do - much less, what the issue really is...

Ineald was configured to just stand there with the purpose of trading one type of dirt for another (as requested by Bob_84 via the bugs-n-stuff channel on our Discord).

**Comment by coder0xff** [comment]
I see. Like Bob_84 said, some mods don't use the ore dictionary which I now understand. I guess he could do more useful stuff. Like, trade many invaluable ores for a more valuable ore. Kinda like currency changing, but with raw materials. That would be awesome.

**Comment by AtaxiaGames-GM** [comment]
I have no problem with doing this, except that I have 18 merchandise slots to play with per trader NPC created. There are already 4 slots used for Ineald. If we want to make Ineald more useful, I will need a list of blocks that players consider valuable for trade.

**Comment by coder0xff** [comment]
Trade tin ore for iron, diamond, red stone. Don't know what else people might consider useful.

**Comment by AtaxiaGames-GM** [comment]
I have modified Ineald's trading to include the following:
12 Tin Ingots = 1 Iron Ingot (purchased in bundles of 5 - is based on the currency exchange rate)
5 Iron Ingots = 1 Redstone (from what I have seen, Iron is about 5 times more abundant than redstone)
12 Iron Ingots = 1 Diamond (from what I have seen, Iron is about 12 times more abundant than diamond)

Please let me know if this suits your request.

**Comment by coder0xff** [comment]
That's awesome. Thanks!

**Comment by AtaxiaGames-GM** [comment]
You're welcome. Let me know if there is anything else I can add for this - commenting should reopen this issue.
